#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}-web" --action="stop" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX Conf AND PRETALX.CFG 
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

# Prepare redis dbs
redis_db=$(ynh_redis_get_free_db)
redis_lock "$redis_db" 

celery_db=$(ynh_redis_get_free_db)
redis_lock "$celery_db"

web_db=$(ynh_redis_get_free_db)

redis_unlock "$redis_db"
redis_unlock "$celery_db"

# Refresh config
ynh_config_add --template="pretalx.cfg" --destination="$install_dir/pretalx.cfg"
chmod 600 "$install_dir/pretalx.cfg"
chown "$app:www-data" "$install_dir/pretalx.cfg"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-web" --action="start" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
