#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

secret_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret_key --value=$secret_key

email=$(ynh_user_get_info --username=$admin --key=mail)
organiser_name=$admin

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=redis_db --value=$redis_db
redis_lock "redis_db" 

celery_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=celery_db --value=$celery_db
redis_unlock "redis_db"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p $install_dir/data/media

chmod -R 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"
chown -R $app:$app "$data_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="pretalx.cfg" --destination="$install_dir/pretalx.cfg"

mkdir -p /var/log/$app
touch /var/log/$app/pretalx.log
touch "/var/log/$app/$app-web.log"
touch "/var/log/$app/$app-worker.log"

chmod 600 "$install_dir/pretalx.cfg"
chown "$app:$app" "$install_dir/pretalx.cfg"
chown -R "$app:$app" "/var/log/$app"


#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
      python3 -m venv $install_dir/venv
      source "$install_dir/venv/bin/activate"

      $install_dir/venv/bin/pip install --upgrade pip setuptools wheel gunicorn django-redis
      $install_dir/venv/bin/pip install --upgrade-strategy eager --upgrade "pretalx[postgres,redis]"
      $install_dir/venv/bin/python3 -m pretalx migrate
      $install_dir/venv/bin/python3 -m pretalx rebuild

      PRETALX_INIT_ORGANISER_NAME="$organiser_name" PRETALX_INIT_ORGANISER_SLUG="$organiser_slug" DJANGO_SUPERUSER_EMAIL="$email" DJANGO_SUPERUSER_PASSWORD="$password" $install_dir/venv/bin/python3 -m pretalx init --noinput

      deactivate
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-web" --template="pretalx-web.service"
ynh_config_add_systemd --service="${app}-worker" --template="pretalx-worker.service"

yunohost service add "${app}-web" --description="Conference management application" --log="/var/log/$app/$app-web.log"
yunohost service add "${app}-worker" --description="Pretalx worker" --log="/var/log/$app/$app-worker.log"

#=================================================
# ADD A CRON JOB
#=================================================

ynh_config_add --template="pretalx.cron" --destination="/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-web" --action="start" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
